<template>
    <div class="fonts-container">
        <div class="dropdown">
            <p>TIPOS DE FONTES</p>
            <div class="dropdown-content">
                <p style="font-family: 'Oswald', sans-serif !important; font-weight: bold" @click='$emit("changefont")' >Oswald</p>
                <p style="font-family:'Zen Loop', cursive !important; font-weight: bold" @click='$emit("changefont")' >Zen Loop</p>
                <p style="font-family: 'Fuggles', cursive; font-weight: bold" @click='$emit("changefont")' >Fuggles</p>
                <p style="font-family': 'STIX Two Math', serif; font-weight: bold" @click='$emit("changefont")' >STIX Two Math</p>
                <p style="font-family: 'Hina Mincho', serif;" @click='$emit("changefont")' >Hina Mincho</p>
                <p style="font-family: 'Inconsolata', monospace;" @click='$emit("changefont")' >Inconsolata</p>
                <p style="font-family: 'Kaisei Decol', serif;" @click='$emit("changefont")' >Kaisei Decol</p>
                <p style="font-family: 'Teko', sans-serif;" @click='$emit("changefont")' >Teko</p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
 name: 'fonts',
}
</script>

<style scoped>
@media screen and(min-width: 1001px) {
    .fonts-container{
    min-height: 100px;
    max-height: 100%;
    width: 100%;
    background-color: white;
}
}
@media screen and(max-width: 1000px) {
    .fonts-container{
        min-height: 50px;
        overflow: scroll;
        width: 100%;
        background-color: white;
    }
}

.pFont:hover{
    background-color: gray;
    color: white;
    box-shadow: whitesmoke -2px -2px;
}
.pFont:active{
    background-color: black;
    color:white;
}
.dropdown p{
    font-weight: bolder;
    margin-left: 20px;
}

.dropdown {
  position: relative;
  display: inline-block;
}
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 12px 16px;
  z-index: 1;
}
.dropdown:hover .dropdown-content {
  display: block;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-9-29 22:25:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

.dropdown-content p:hover{
  background-color: gray;
}
</style>